class Champion {
  constructor(name, cost) {
    this.name = name;
    this.cost = cost;
  }
}

window.champions = [
	new Champion('Diana', 1),
	new Champion('Elise', 1),
	new Champion('Fiora', 1),
	new Champion('Garen', 1),
	new Champion('Lissandra', 1),
	new Champion('Maokai', 1),
	new Champion('Nami', 1),
	new Champion('Nidalee', 1),
	new Champion('Tahm Kench', 1),
	new Champion('Twisted Fate', 1),
	new Champion('Vayne', 1),
	new Champion('Wukong', 1),
	new Champion('Yasuo', 1),
	new Champion('Annie', 2),
	new Champion('Aphelios', 2),
	new Champion('Hecarim', 2),
	new Champion('Janna', 2),
	new Champion('Jarvan IV', 2),
	new Champion('Jax', 2),
	new Champion('Lulu', 2),
	new Champion('Pyke', 2),
	new Champion('Sylas', 2),
	new Champion('Teemo', 2),
	new Champion('Thresh', 2),
	new Champion('Vi', 2),
	new Champion('Zed', 2),
	new Champion('Akali', 3),
	new Champion('Evelynn', 3),
	new Champion('Irelia', 3),
	new Champion('Jinx', 3),
	new Champion('Kalista', 3),
	new Champion('Katarina', 3),
	new Champion('Kennen', 3),
	new Champion('Kindred', 3),
	new Champion('Lux', 3),
	new Champion('Nunu', 3),
	new Champion('Veigar', 3),
	new Champion('Xin Zhao', 3),
	new Champion('Yuumi', 3),
	new Champion('Aatrox', 4),
	new Champion('Ahri', 4),
	new Champion('Ashe', 4),
	new Champion('Cassiopeia', 4),
	new Champion('Jhin', 4),
	new Champion('Morgana', 4),
	new Champion('Riven', 4),
	new Champion('Sejuani', 4),
	new Champion('Shen', 4),
	new Champion('Talon', 4),
	new Champion('Warwick', 4),
	new Champion('Azir', 5),
	new Champion('Ezreal', 5),
	new Champion('Kayn', 5),
	new Champion('Lee Sin', 5),
	new Champion('Lillia', 5),
	new Champion('Sett', 5),
	new Champion('Yone', 5),
	new Champion('Zilean', 5)
];